import { useState } from 'react';

interface ExportButtonProps {
    generatedLesson: {
        title?: string;
        lesson?: string;
        generatedAt?: string;
        inputLength?: number;
        exercises?: any[];
    };
}

export default function ExportButton({ generatedLesson }: ExportButtonProps) {
    const [isExporting, setIsExporting] = useState(false);

    const handleExport = () => {
        setIsExporting(true);
        try {
            const content = `# ${generatedLesson.title || 'Lección Sandbox'}\n\n${generatedLesson.lesson}\n\nGenerated by AI Code Mentor`;
            const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
            const url = URL.createObjectURL(blob);
            const link = document.body.appendChild(document.createElement('a'));
            link.href = url;
            link.download = `leccion-${Date.now()}.md`;
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
        } finally {
            setIsExporting(false);
        }
    };

    return (
        <button
            onClick={handleExport}
            disabled={isExporting}
            className="bg-green-600 text-white px-4 py-3 rounded-lg font-bold disabled:opacity-50"
        >
            {isExporting ? 'Exportando...' : '📥 Exportar .md'}
        </button>
    );
}
